@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzI2NzU2NzYwLCJleHAiOjE3MjY3NTg1NjB9.5pb4KXVq6xbj8Pi4oSbaX2kfNMGqGi7jcO17knSfJi4
### Obtener todos los pedidos (Admin)
GET http://localhost:9000/pedidos
Authorization: Bearer {{token}}

### Obtener pedidos del usuario autenticado
GET http://localhost:9000/pedidos/usuario
Authorization: Bearer {{token}}

### Obtener pedido por id
GET http://localhost:9000/pedidos/2
Authorization: Bearer {{token}}

### Crear un nuevo pedido (Usuario autenticado)
POST http://localhost:9000/pedidos
Authorization: Bearer {{token}}
Content-Type: application/json

{
    
    "platos": [
    {
        "id": 1,
        "cantidad": 2
    },
    {
        "id": 2,
        "cantidad": 1
    }
    ]
}

### Aceptar pedido (Admin)
PUT http://localhost:9000/pedidos/1/aceptar
Authorization: Bearer {{token}}

### Comenzar pedido (Admin)
PUT http://localhost:9000/pedidos/1/comenzar
Authorization: Bearer {{token}}

### Entregar pedido (Admin)
PUT http://localhost:9000/pedidos/1/entregar
Authorization: Bearer {{token}}

### Eliminar un pedido (Admin)
DELETE http://localhost:9000/pedidos/5
Authorization: Bearer {{token}}