@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzI3MDk3NzU5LCJleHAiOjE3MjcwOTk1NTl9.mqJQbV6mZd8IRmkYOvPpXoOID30brPmDBTGQyI0PrhA

### make admin route
GET http://localhost:9000/usuarios/makeadmin/4
Authorization: Bearer {{token}}